local M = {}

-- custom icons (mostly used in cmp)
M.icons = {
  File = " ",
  Module = "  ",
  Namespace = " ",
  Package = " ",
  Class = "ﴯ  ",
  Method = "  ",
  Property = "ﰠ  ",
  Field = "ﰠ  ",
  Constructor = "  ",
  Enum = "  ",
  Interface = "  ",
  Function = "  ",
  Variable = "  ",
  Constant = " ",
  String = " ",
  Number = " ",
  Boolean = "◩ ",
  Array = " ",
  Object = " ",
  Key = " ",
  Null = "ﳠ ",
  EnumMember = "  ",
  Struct = "פּ  ",
  Event = " ",
  Operator = "  ",
  Text = "  ",
  TypeParameter = "  ",
  Unit = "塞 ",
  Value = "  ",
  Keyword = "  ",
  Snippet = "ﲆ  ",
  Snippetes = "ﲆ  ",
  Color = "  ",
  Folder = "  ",
  Database = " ",
}

return M
